[package]
name = "day20-2"
version = "0.1.0"
authors = ["Andy <andy.ward.uk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
